myvector: myvector.h unittest.cpp

	g++ -std=c++11 -isystem ../../3p/gtest-1.7.0/include -pthread myvector.h unittest.cpp ../../3p/gtest-1.7.0/libgtest.a

clean:

	rm a.out myvector.h.gch

debug:

	g++ -g -std=c++11 -isystem ../../3p/gtest-1.7.0/include -pthread myvector.h unittest.cpp ../../3p/gtest-1.7.0/libgtest.a
